name: outputtest workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: g++ -std=c++17 *.cpp
      - name: Run output test
        run: test/run_test.sh
      - name: Diff
        run: diff test/output.txt test/units/good_output.txt
      - name: Run parser test
        run: test/parserTest
