name: test workflow

on:
  push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies for valgrind and cppcheck
        run: sudo apt-get install -y valgrind cppcheck
      - name: Run makefile
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          path: ./cppreport.txt
      - name: Run test
        run: ./run_test.sh
      - name: Diff
        run: diff output.txt test/units/good_output.txt