name: Run tests

on:
  push

jobs:
  runtests:
    name: Run cppcheck, valgrind and diff
    runs-on: ubuntu-latest
    container: rolandborbely/tests-image:latest 
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Installing valgrind and cppcheck'
      - name: run Makefile
        run: make tests
      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          path: ./cppreport.txt
  unittest:
    name: Run Unit test
    runs-on: ubuntu-latest
    container: rolandborbely/tests-image:latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'Installing dependencies for the unit tests'
      - name: Make build environment
        run: cd /usr/src/gtest && cmake CMakeLists.txt && make
      - name: Create references
        run: ln -st /usr/lib/ /usr/src/gtest/libgtest.a && ln -st /usr/lib/ /usr/src/gtest/libgtest_main.a
      - name: Run test
        run: make unittest